apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: substrate-api
spec:
  selector:
    matchLabels:
      app: substrate-api
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
